[project]
name = "RamTorch"
version = "1.5.1"
authors = [{name = "Lodestone", email = "lodestone.rock@gmail.com"}]
description = "RAM is All You Need"
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "Intended Audience :: Education",
    "Intended Audience :: Science/Research",
    "Operating System :: OS Independent",
    "Topic :: Scientific/Engineering :: Artificial Intelligence",
    "Programming Language :: Python :: 3",
]

[project.urls]
Homepage = "https://github.com/lodestone-rock/RamTorch"

[tool.setuptools.packages.find]
include = ["ramtorch*"]
exclude = ["examples*", "env*", "scraped*", "kernels*", "data*", "tests*"]

[tool.setuptools]
license-files = []